// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCenE2V53epPg7sOFEnULbBA4aDqEvleGk',
    appId: '1:142254320964:web:8f1f923c5f308c1098fb11',
    messagingSenderId: '142254320964',
    projectId: 'darzo-app-7722a',
    authDomain: 'darzo-app-7722a.firebaseapp.com',
    storageBucket: 'darzo-app-7722a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDer_tHgYQ_wYbbEgWdIu6gRHgBwjbTAu0',
    appId: '1:142254320964:android:3671ba92477f9ad498fb11',
    messagingSenderId: '142254320964',
    projectId: 'darzo-app-7722a',
    storageBucket: 'darzo-app-7722a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4i9e9tQLsMRSG5aOg-QbJX_CclMkywZ0',
    appId: '1:142254320964:ios:dea73d9e0cb8295798fb11',
    messagingSenderId: '142254320964',
    projectId: 'darzo-app-7722a',
    storageBucket: 'darzo-app-7722a.firebasestorage.app',
    iosBundleId: 'com.example.darzo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4i9e9tQLsMRSG5aOg-QbJX_CclMkywZ0',
    appId: '1:142254320964:ios:dea73d9e0cb8295798fb11',
    messagingSenderId: '142254320964',
    projectId: 'darzo-app-7722a',
    storageBucket: 'darzo-app-7722a.firebasestorage.app',
    iosBundleId: 'com.example.darzo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCenE2V53epPg7sOFEnULbBA4aDqEvleGk',
    appId: '1:142254320964:web:b7bac2408020105398fb11',
    messagingSenderId: '142254320964',
    projectId: 'darzo-app-7722a',
    authDomain: 'darzo-app-7722a.firebaseapp.com',
    storageBucket: 'darzo-app-7722a.firebasestorage.app',
  );

}